import { useMemo, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router';
import { ArrowLeft, ArrowRight, Check, FileSpreadsheet, Upload } from 'lucide-react';
import { useApp } from '../app/context';
import { importEvent, message } from '../lib/supabase';
import { readSpreadsheet, suggestMapping, validateSheet, type Mapping, type Sheet } from '../lib/parsing';

export function ImportWizard() {
  const { profile, demo } = useApp(); const navigate = useNavigate();
  const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [details, setDetails] = useState({ name: '', event_date: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, venue: '' });
  const [sheets, setSheets] = useState<Sheet[]>([]); const [sheetIndex, setSheetIndex] = useState(0);
  const [filename, setFilename] = useState(''); const [mapping, setMapping] = useState<Mapping>({ ticket: -1, name: -1, first: -1, last: -1, email: -1 });
  const requestId = useRef<string | null>(null);
  const sheet = sheets[sheetIndex];
  const validation = useMemo(() => sheet ? validateSheet(sheet, mapping) : null, [sheet, mapping]);
  const changeDetails = (field: keyof typeof details, value: string) => { requestId.current = null; setDetails(d => ({ ...d, [field]: value })); };
  if (profile.role !== 'organiser') return <div className="alert error">Only organisers can create events.</div>;
  const upload = async (file?: File) => {
    if (!file) return;
    setBusy(true); setError(''); requestId.current = null; setSheets([]);
    try { const parsed = await readSpreadsheet(file); if (!parsed.length) throw new Error('No worksheets found.'); setSheets(parsed); setSheetIndex(0); setMapping(suggestMapping(parsed[0].headers)); setFilename(file.name); }
    catch (e) { setError(message(e)); } finally { setBusy(false); }
  };
  const save = async () => {
    if (demo) { setError('Preview mode cannot save events. Connect Supabase first.'); return; }
    if (!validation || validation.errors.length) return;
    setBusy(true); setError(''); requestId.current ??= crypto.randomUUID();
    try { const id = await importEvent(details, validation.attendees, requestId.current); navigate(`/events/${id}`); }
    catch (e) { setError(message(e) + ' You can retry safely with the same import request.'); } finally { setBusy(false); }
  };
  return <><Link className="back-link" to="/"><ArrowLeft size={16}/> All events</Link><div className="page-heading"><div><span className="eyebrow">MAKE ROOM FOR A GREAT EVENT</span><h1>Create an event<span className="green">.</span></h1><p className="muted">Bring your attendee list. We’ll take care of the welcome.</p></div></div><div className="wizard-steps">{['Event details', 'Attendee file', 'Map columns', 'Review & create'].map((label, i) => <div className={step === i ? 'current' : step > i ? 'done' : ''} key={label}><span>{step > i ? <Check size={15}/> : i + 1}</span>{label}</div>)}</div><section className="panel wizard-panel">{error && <div className="alert error" role="alert">{error}</div>}
    {step === 0 && <form onSubmit={e => { e.preventDefault(); try { new Intl.DateTimeFormat(undefined, { timeZone: details.timezone }); setError(''); setStep(1); } catch { setError('Enter a valid IANA timezone, such as America/New_York.'); } }}><h2>First, the essentials.</h2><p className="muted">Give your team the details they need.</p><label>Event name<input required maxLength={200} value={details.name} onChange={e => changeDetails('name', e.target.value)} placeholder="e.g. Community Gala 2026"/></label><div className="form-grid"><label>Event date<input type="date" required value={details.event_date} onChange={e => changeDetails('event_date', e.target.value)}/></label><label>Event timezone<input required value={details.timezone} onChange={e => changeDetails('timezone', e.target.value)} placeholder="America/New_York"/></label></div><label>Venue <span className="muted">(optional)</span><input maxLength={300} value={details.venue} onChange={e => changeDetails('venue', e.target.value)} placeholder="Where are we gathering?"/></label><div className="wizard-actions"><span/><button className="button primary">Continue <ArrowRight size={17}/></button></div></form>}
    {step === 1 && <><h2>Bring your guest list.</h2><p className="muted">CSV or Excel (.xlsx), up to 5 MB and 5,000 attendees.</p><label className="upload-zone"><Upload size={35}/><strong>{busy ? 'Reading your file…' : filename || 'Choose your attendee file'}</strong><span>Ticket codes must be the exact text encoded in your existing QR codes.</span><input type="file" accept=".csv,.xlsx" disabled={busy} onChange={e => void upload(e.target.files?.[0])}/></label>{sheets.length > 0 && <label>Worksheet<select value={sheetIndex} onChange={e => { const index = +e.target.value; setSheetIndex(index); setMapping(suggestMapping(sheets[index].headers)); requestId.current = null; }}>{sheets.map((s, i) => <option key={i} value={i}>{s.name} · {s.rows.length} source rows</option>)}</select></label>}<div className="info-note"><FileSpreadsheet size={19}/><span>We parse the file in your browser. QR images and unmapped formula columns are ignored. The original file is not stored or modified.</span></div><div className="wizard-actions"><button className="button secondary" onClick={() => setStep(0)}>Back</button><button className="button primary" disabled={!sheets.length || busy} onClick={() => setStep(2)}>Map columns <ArrowRight size={17}/></button></div></>}
    {step === 2 && sheet && <><h2>Match your columns.</h2><p className="muted">Column names and order can vary. Confirm the suggestions below.</p>{([['ticket', 'Ticket code *'], ['name', 'Full name'], ['first', 'First name (if no full name)'], ['last', 'Last name (if no full name)'], ['email', 'Email (optional)']] as const).map(([field, label]) => <label key={field}>{label}<select value={mapping[field]} onChange={e => { setMapping(m => ({ ...m, [field]: +e.target.value })); requestId.current = null; }}><option value={-1}>Not mapped</option>{sheet.headers.map((h, i) => <option key={i} value={i}>{i + 1}. {h || '(blank heading)'}</option>)}</select></label>)}<div className="wizard-actions"><button className="button secondary" onClick={() => setStep(1)}>Back</button><button className="button primary" onClick={() => setStep(3)}>Review import <ArrowRight size={17}/></button></div></>}
    {step === 3 && validation && <><h2>A quick look before we begin.</h2><p className="muted">{details.name} · {validation.attendees.length} attendees · {validation.skipped} blank rows skipped</p>{validation.errors.length > 0 && <div className="alert error"><strong>{validation.errors.length} issue(s) to fix</strong><ul>{validation.errors.slice(0, 30).map((e, i) => <li key={i}>{e}</li>)}</ul>{validation.errors.length > 30 && <p>Showing first 30 issues. Correct the source file and upload again.</p>}</div>}{validation.warnings.length > 0 && <div className="alert warning"><strong>Check numeric ticket codes before confirming.</strong><ul>{validation.warnings.slice(0, 10).map((w,i) => <li key={i}>{w}</li>)}</ul></div>}<div className="table-scroll"><table><thead><tr><th>Ticket code</th><th>Attendee name</th><th>Email</th></tr></thead><tbody>{validation.attendees.slice(0, 10).map((a, i) => <tr key={i}><td className="mono">{a.ticket_code}</td><td>{a.name}</td><td>{a.email || '—'}</td></tr>)}</tbody></table></div><p className="small muted">Preview shows the first 10 attendees. The complete import is saved together, or not at all.</p><div className="wizard-actions"><button className="button secondary" disabled={busy} onClick={() => setStep(2)}>Back</button><button className="button primary" disabled={busy || validation.errors.length > 0} onClick={() => void save()}>{busy ? 'Creating event…' : 'Confirm & create event'} <Check size={17}/></button></div></>}
  </section></>;
}
